### ISSUE TITLE
Build failure on GNU Make and non-BSD systems

### ISSUE THREAD

**Issue by N-R-K** [omar-polo/mymenu#1]
The README states to simply run `make`, but that does not work on GNU Make which gives the following error:

```console
$ make
Makefile:1: *** missing separator.  Stop.
```

Also the source uses some BSD extensions (such as `recallocarray`) which means `libbsd` will need to be a dependency on non-BSD systems. Additionally `$(pkg-config --cflags libbsd-overlay)` needs to added to `CPPFLAGS` for `libbsd` to work on "overlay" mode. Also `_GNU_SOURCE` needs to be defined for `strcasestr` on `glibc` systems.

**Comment by omar-polo** [comment]
Hi!

Yes, in fd3ba448dccd71ffa0e7dd708fdb6bd2e021203d I reworked the Makefile a bit and used some OpenBSD-specific things.  (and forgot to update the README by the way!)

I do care about portability, but admittedly not in this project.  Not for a specific reason, it's just that mymenu was one of the first C program I wrote years ago and didn't thought anyone would except me would use it! :D

Anyway, it shouldn't be a bad idea to make it portable.  I'll try to do something (probably with [Kristaps' oconfigure](https://github.com/kristapsdz/oconfigure)) during the weekend.

Thanks,

**Comment by omar-polo** [comment]
it was easier than what I thought :)

the `master` branch now has a configure script and a portable Makefile.  I tested them on OpenBSD and on alpine linux.  it also contains a copy of the non-standard functions I'm using, so libbsd is not a hard dependency (it's still possible to use it however if wanted.)

**Comment by N-R-K** [comment]
Yes, this works now. However I'd like to point out that depending on `libbsd` isn't a bad thing, it's quite widely available on various distros. My problem was the fact that it was *not documented*.

In fact, I at least prefer documenting deps over configure scripts. It's then the installer's (which might be a package manger or user compiling from source) responsibility to make sure that either the deps are met or to disable optional deps via relevant settings, e.g `make HAVE_STRCASESTR=0`.

But `oconfigure` isn't as bad as autohell, so it's not that big of a deal :)

---

Anyhow, a couple warnings which got raised:

```console
mymenu.c: In function 'text_extents':
mymenu.c:456:43: warning: pointer targets in passing argument 3 of 'XftTextExtentsUtf8' differ in signedness [-Wpointer-sign]
  456 |         XftTextExtentsUtf8(r->d, r->font, str, len, &gi);
      |                                           ^~~
      |                                           |
      |                                           char *
In file included from mymenu.c:36:
/usr/include/X11/Xft/Xft.h:321:38: note: expected 'const FcChar8 *' {aka 'const unsigned char *'} but argument is of type char *'
  321 |                     _Xconst FcChar8 *string,
      |                                      ^
mymenu.c: In function 'draw_string':
mymenu.c:479:65: warning: pointer targets in passing argument 6 of 'XftDrawStringUtf8' differ in signedness [-Wpointer-sig]
  479 |         XftDrawStringUtf8(r->xftdraw, &xftcolor, r->font, x, y, str, len);
      |                                                                 ^~~
      |                                                                 |
      |                                                                 char *
In file included from mymenu.c:36:
/usr/include/X11/Xft/Xft.h:224:38: note: expected 'const FcChar8 *' {aka 'const unsigned char *'} but argument is of type char *'
  224 |                    _Xconst FcChar8  *string,
      |                                      ^
mymenu.c: In function 'parse_color':
mymenu.c:938:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
  938 |                 tmp.v = (tmp.v & 0xf00) * 0x1100 | (tmp.v & 0x0f0) * 0x0110
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  939 |                         | (tmp.v & 0x00f) * 0x0011;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
mymenu.c:940:9: note: here
  940 |         case 6:
      |         ^~~~
```

The first two should just be a matter of casting. Not sure about the 3rd (didn't look into it). And FYI, there's `XAllocNamedColor(3)` which can parse color strings (it'd work even on "white", "black" etc, not just hexcolors).

**Comment by omar-polo** [comment]
> However I'd like to point out that depending on libbsd isn't a bad thing, it's quite widely available on various distros.

I don't consider it a bad thing, I just wanted to avoid an extra dependency.  It's still possible to use it, and the configure script will avoid building the compat if you pass the flags for libbsd.  I'll add an example to the README.

> In fact, I at least prefer documenting deps over configure scripts. It's then the installer's (which might be a package manger or user compiling from source) responsibility to make sure that either the deps are met or to disable optional deps via relevant settings, e.g make HAVE_STRCASESTR=0.

Have to agree on this one, but on the other hand I also wanted the build to be simple :)

I've stolen a trick mandoc-portable does and included a `configure.local.example` file which can be used as a base for `configure.local`, which is used by the configure script to avoid the autoconfiguration if wanted.  (still have to update the readme about this)  In addition, every check the configure script does is printed both to a log file and to stderr, so for a packager it should be easy to see what's going on and tweak it eventually.

Regarding the issues, I'm personally not too fond of the -Wpointer-sign, in this case in particular it makes the code more ugly than what it should fix.  I've pushed a "fix" for the third one, the one regarding the fallthrough, as in that case it was wanted.

I'll look into XAllocNamedColor(3), I wrote that code four year ago and I'm not sure if I haven't used it on purpose or just didn't know about it.

Thanks!

**Comment by N-R-K** [comment]
Btw gcc at `-Wimplicit-fallthrough` level 3 (which is the default) checks for the following regular expression in comments (from the gcc manpage):

```
*<-Wimplicit-fallthrough=3 case sensitively matches one of the>
    following regular expressions:

    *<"-fallthrough">
    *<"@fallthrough@">
    *<"lint -fallthrough[ \t]*">
    *<"[ \t.!]*(ELSE,? |INTENTIONAL(LY)? )?FALL(S | |-)?THR(OUGH|U)[ \t.!]*(-[^\n\r]*)?">
    *<"[ \t.!]*(Else,? |Intentional(ly)? )?Fall((s | |-)[Tt]|t)hr(ough|u)[ \t.!]*(-[^\n\r]*)?">
    *<"[ \t.!]*([Ee]lse,? |[Ii]ntentional(ly)? )?fall(s | |-)?thr(ough|u)[ \t.!]*(-[^\n\r]*)?">
```

In other words, the comment needs to be `/* fallthrough */` not `/* fallback */`.

**Comment by omar-polo** [comment]
wooops, that's what I get for trying to fix a warning without checking if the compiler is really happy about it.  Fixed, sorry!

Thanks

**Comment by N-R-K** [comment]
Great, compiles fine without any warning or fuss now!
